# Generated by Django 4.2 on 2023-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
